<a href="https://colab.research.google.com/github/MinhajurRFahad/Pytorch/blob/main/Logistic/Softmax%20regression%20and%20Cross%20Entropy%20Loss%20with%20PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Synthetic** **Data** **Generation**

In [2]:
import torch

In [3]:
from torch.utils import data

In [4]:
def synthetic_data(w, b, num_examples):
  # y= Xw + b + noise
  X = torch.normal(0, 1, (num_examples, len(w)))
  y = torch.matmul(X, w) + b
  y += torch.normal(0, 0.01, y.shape)
  return X, y.reshape((-1, 1))

In [5]:
true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = synthetic_data(true_w, true_b, 1000)
features.shape, labels.shape

(torch.Size([1000, 2]), torch.Size([1000, 1]))

Step 1: Reading the data set

In [17]:
def load_array(data_arrays, batch_size, is_train=True):
#Construct a python data iterator
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

In [18]:
batch_size = 10
data_iter = load_array((features, labels), batch_size)

Step 2: Defining the model

In [19]:
from torch import nn

In [20]:
net = nn.Sequential(nn.Linear(2, 1))

In [21]:
net[0].weight, net[0].bias

(Parameter containing:
 tensor([[-0.1214,  0.6766]], requires_grad=True),
 Parameter containing:
 tensor([-0.2946], requires_grad=True))

In [23]:
#initializa w1, w2, and b
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

Step 3: Defining the cost function and Optimizer

In [26]:
loss = nn.MSELoss()
trainer = torch.optim.SGD(net.parameters(), lr=0.03)